CREATE TABLE "Details" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TypeDetail" integer NOT NULL,
    "Name" character varying(1000) NULL,
    "Measurement" character varying(250) NULL,
    "Price" numeric NOT NULL,
    CONSTRAINT "PK_Details" PRIMARY KEY ("Id")
);

CREATE TABLE "Operations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Operations" PRIMARY KEY ("Id")
);

CREATE TABLE "Professions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    CONSTRAINT "PK_Professions" PRIMARY KEY ("Id")
);

CREATE TABLE "Tarifs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CountPerHour" integer NOT NULL,
    "StandartId" integer NOT NULL,
    CONSTRAINT "PK_Tarifs" PRIMARY KEY ("Id")
);

CREATE TABLE "Standarts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OperationId" integer NOT NULL,
    "CodeProfession" integer NOT NULL,
    "DischargeBuilder" integer NOT NULL,
    "TarifId" integer NOT NULL,
    "TimeEnsure" time without time zone NOT NULL,
    "ValuePerTime" time without time zone NOT NULL,
    CONSTRAINT "PK_Standarts" PRIMARY KEY ("Id"),
    CONSTRAINT "DischargeBuilder" CHECK ("DischargeBuilder" > 0 AND "DischargeBuilder" < 9),
    CONSTRAINT "FK_Standarts_Operations_OperationId" FOREIGN KEY ("OperationId") REFERENCES "Operations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Standarts_Tarifs_TarifId" FOREIGN KEY ("TarifId") REFERENCES "Tarifs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Standarts_OperationId" ON "Standarts" ("OperationId");

CREATE UNIQUE INDEX "IX_Standarts_TarifId" ON "Standarts" ("TarifId");
